In [2]:
import torch
def synthetic_data(w, b, num_examples):
    X=torch.normal(0,1,(num_examples,len(w)))
    y=torch.matmul(X,w)+b
    y+=torch.normal(0,0.01,y.shape)
    return X, y

In [3]:
true_w=torch.tensor([[2],[-3.4]])
true_b=4.2
features,labels=synthetic_data(true_w,true_b,1000)
print(features,labels)

tensor([[-0.1434, -0.4008],
        [-0.4254,  0.6257],
        [ 0.1535,  0.0741],
        ...,
        [-2.6066, -0.9244],
        [ 1.4255,  1.1512],
        [-0.6218,  0.8301]]) tensor([[ 5.2696e+00],
        [ 1.2270e+00],
        [ 4.2797e+00],
        [ 3.3656e+00],
        [-4.5509e-02],
        [-7.9203e-01],
        [ 6.7675e+00],
        [ 4.8067e+00],
        [ 6.8284e+00],
        [ 1.2177e+01],
        [ 5.2794e+00],
        [ 4.6474e+00],
        [ 2.9370e+00],
        [ 5.1649e+00],
        [ 3.2991e+00],
        [ 2.8185e+00],
        [ 5.6401e+00],
        [ 1.3788e+01],
        [ 8.5039e-01],
        [ 8.7015e+00],
        [ 5.4434e+00],
        [ 1.1144e+01],
        [ 5.5128e+00],
        [-5.7169e-01],
        [ 5.6335e+00],
        [-1.0731e+00],
        [ 6.8382e-01],
        [ 4.3340e+00],
        [ 4.3718e+00],
        [ 2.9844e+00],
        [-1.7476e+00],
        [ 1.0108e+01],
        [-4.6403e+00],
        [ 9.4854e+00],
        [ 5.4880e+00],
        [ 5.0

In [10]:
# 自己写的
import random
def data_iter(batch_size,features,labels):
    num_examples=len(features)
    index=list(range(num_examples))
    random.shuffle(index)
    for i in range(0,num_examples,batch_size):
        batch_index=index[i:min(i+batch_size,num_examples)]
        yield features[batch_index] , labels[batch_index]

        
batch_size=10
for X,y in data_iter(batch_size,features,labels):
    print(X,y)


tensor([[-1.7393, -1.9929],
        [-0.0408,  0.4696],
        [-0.8740,  1.4379],
        [ 0.1469, -2.1549],
        [ 0.5721, -1.0448],
        [ 0.3981,  1.1395],
        [ 2.3628,  0.8456],
        [-1.1164,  0.4507],
        [ 1.3010, -1.3304],
        [-1.4509,  1.6367]]) tensor([[ 7.5014],
        [ 2.5158],
        [-2.4362],
        [11.8160],
        [ 8.8798],
        [ 1.1307],
        [ 6.0364],
        [ 0.4370],
        [11.3185],
        [-4.2530]])
tensor([[-1.2438,  0.1728],
        [ 1.0071,  1.0228],
        [ 0.7185, -0.4586],
        [ 1.3680, -0.4377],
        [-0.3342,  1.9562],
        [-0.6457, -0.4640],
        [ 0.3166, -1.2698],
        [-2.2693, -0.5425],
        [-0.7930, -0.8699],
        [-1.4247,  1.3531]]) tensor([[ 1.1326],
        [ 2.7530],
        [ 7.1944],
        [ 8.4586],
        [-3.1082],
        [ 4.4941],
        [ 9.1440],
        [ 1.5151],
        [ 5.5694],
        [-3.2580]])
tensor([[ 0.2589,  0.4461],
        [-0.6721, -1.0191],


In [23]:
# 定义模型、损失函数和优化算法
def linreg(X,w,b):
    return torch.matmul(X,w)+b

def squared_loss(y_hat,y):
    return (y_hat-y.reshape(y_hat.shape))**2/2

def optimizer(params,lr,batch_size):
    with torch.no_grad():
        for param in params:
            param-=lr*param.grad/batch_size
            param.grad.zero_()



In [24]:
# 初始化模型
w=torch.normal(0,0.01,size=(2,1),requires_grad=True)
b=torch.zeros(1,requires_grad=True)
# 创建模型
# 其实这里好像不用
net=linreg
loss=squared_loss
# 定义超参数
lr=0.01
batch_size=100
num_epochs=3
# 训练模型
for epoch in range(num_epochs):
    for X,y in data_iter(batch_size,features,labels):
        l=loss(net(X,w,b),y)
        l.sum().backward()
        optimizer([w,b],lr,batch_size)
    with torch.no_grad():
        train_loss=loss(net(features,w,b),labels)
        print(f'epoch {epoch+1} loss {train_loss.sum()/len(features)}')




epoch 1 loss 12.940266609191895
epoch 2 loss 10.708128929138184
epoch 3 loss 8.86107349395752
